# Generated by Django 3.1 on 2021-06-23 11:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('chartapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='chart',
            name='parentproject',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='chartapp.project'),
        ),
    ]
