# Generated by Django 3.1 on 2021-06-26 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chartapp', '0004_auto_20210623_1419'),
    ]

    operations = [
        migrations.AddField(
            model_name='chart',
            name='color',
            field=models.CharField(choices=[('rgba(255, 99, 132, 1)', 'Red'), ('rgba(54, 162, 235, 1)', 'Blue'), ('rgba(255, 206, 86, 1)', 'Yellow'), ('rgba(75, 192, 192, 1)', 'Green'), ('rgba(153, 102, 255, 1)', 'Purple'), ('rgba(255, 159, 64, 1)', 'Orange')], default='rgba(0, 0, 0, 0.1)', max_length=40),
        ),
        migrations.AlterField(
            model_name='chart',
            name='data_list',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='chart',
            name='inner_labels',
            field=models.TextField(),
        ),
    ]
