# Generated by Django 3.1 on 2021-06-26 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chartapp', '0005_auto_20210626_1144'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chart',
            name='labels',
        ),
        migrations.AddField(
            model_name='chart',
            name='label',
            field=models.CharField(default='-', max_length=100),
        ),
        migrations.AddField(
            model_name='chart',
            name='type',
            field=models.CharField(choices=[('rgba(255, 99, 132, 1)', 'Red'), ('rgba(54, 162, 235, 1)', 'Blue'), ('rgba(255, 206, 86, 1)', 'Yellow'), ('rgba(75, 192, 192, 1)', 'Green'), ('rgba(153, 102, 255, 1)', 'Purple'), ('rgba(255, 159, 64, 1)', 'Orange')], default='bar', max_length=40),
        ),
    ]
