# Generated by Django 3.1 on 2021-06-26 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chartapp', '0006_auto_20210626_1151'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chart',
            name='color',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='chart',
            name='type',
            field=models.CharField(choices=[('bar', 'Bar Graph'), ('line', 'Line Graph'), ('pie', 'Pie Chart'), ('doughnut', 'Doughnut Chart')], default='bar', max_length=40),
        ),
    ]
